json.extract! @robot, :id,
                      :name,
                      :manufacturer,
                      :location,
                      :image_url,
                      :video_url,
                      :created_at,
                      :comments,
                      :price,
                      :description,
                      :updated_at
